### ISSUE TITLE
Parsing not sucessful anymore

### ISSUE THREAD

**Issue by GehriJan** [satoqz/rapla-proxy#11]
## Description
Parsing isnt succesfull, but just displayes _"Bad request"_.
Last semester it was sucessful, so idk what causes the problem. If I try parsing last semesters Rapla to iCal it works, but chrome states the file to be dangerous (while Safari and Firefox Developer dont complain)
Maybe it is due to a change in the Rapla Key Format. Parsing with the old key still works.
## Here are the keys:
**Old (succesfull, but "dangerous"):** txB1FOi5xd1wUJBWuX8lJrog1ZNPBrE7IVuW7j2dZDqE0V49uk4ZZWgywa_ubUu4&day=16&month=6&year=2023&next=>>
**New (not succesfull):** 6Q0QSbNtpyeYPKQhnGFTaEN6AggaPdGgCFyhd5ANmjydX8WyDjUfLBh4YjDgat2dJd8as6Az5GGmQilBwJydDQ9mOxf_r9QyANROJjnM532B_QwXlNZvuyZyN6GRVQyM&salt=648736798&day=23&month=10&year=2023&goto=Datum+anzeigen&pages=1

### macOS:
| Browser | Old | New |
|--------|--------|--------|
| Chrome | "Dangerous" | "Bad Request" |
| Safari | Works | "Bad Request" |
| Firefox Developer | Works | "Bad Request" | 
### Windows
| Browser | Old | New |
|--------|--------|--------|
| Chrome | "Dangerous" | "Bad Request" |

**Comment by satoqz** [comment]
With the switch to rapla.dhbw.net and a new URL format this semester, DHBW also introduced a new format for the calendar on the Rapla site, thus parsing is broken. I'll get to this once I have the time (< 1 month) - it looks like this will be slightly more difficult to parse.

Regarding Chrome, no idea what Google is doing there. It's literally a bunch of text served over HTTPS.

**Comment by satoqz** [comment]
@GehriJan I've just merged and deployed a new version that is now geared towards the updated Rapla calendar page. Make sure to visit the README for the required set up steps, as I've made breaking changes to the "API" of the service, accounting for the new URL format used. Please let me know if you face any problems :)

**Comment by GehriJan** [comment]
@satoqz It works now, thats great. Thanks a lot. Your service helps me really dodging the web-view and integrating it in my calender.
Maybe you could add information about "&gotoDatum" and "&salt", bc i wasnt shure wether to leave them in the url or to remove them. left them and it works. Thanks again!

**Comment by GehriJan** [comment]
closing...

**Comment by satoqz** [comment]
@GehriJan I agree that the URL setup isn't user-friendly enough. I've just deployed a change such that it doesn't matter what exactly the query parameters are - the URL is automatically transformed to the correct version internally. All you now need to do is change the hostname from `dhbw.de` to `satoqz.net`.
